### ISSUE TITLE
Retrieve administrative status from the meter

### ISSUE THREAD

**Issue by elhachhouchi** [OSGP/Protocol-Adapter-DLMS#37]
### See story osgp/platform#190 for details
```
```

### Story
```
As a grid operator
I want to be able to get the administration status of a meter, FROM THE METER
So that I can see if the meter might  be read out via P3
```

**Comment by carlogeenen** [comment]
Testresults:

Get administrative status works fine in Demo App
Set administrative status works fine in Demo App
Get administrative status works fine in SoapUI
Set administrative status does not work correctly in SoapUI
GetSetAdministrativeStatusResponse returns: [Schema Compliance] Expected element 'Description@http://www.alliander.com/schemas/osgp/smartmetering/sm-configuration/2014/10' before the end of the content in element SetAdministrativeStatusResponse@http://www.alliander.com/schemas/osgp/smartmetering/sm-configuration/2014/10

Last mentioned issue does not concern functionality of this issue and the testcase.
It occurs with at this moment with OSGP_Protocol-Adapter-DLMS_development build #81.
However, it doesn't occur when using local WSDL and XSD files, this will be investigated.

**Comment by carlogeenen** [comment]
Testresults:

Get administrative status works fine in SoapUI
Set administrative status does not work correctly in SoapUI
GetSetAdministrativeStatusResponse returns: [Schema Compliance] Expected element 'Description@http://www.alliander.com/schemas/osgp/smartmetering/sm-configuration/2014/10' before the end of the content in element SetAdministrativeStatusResponse@http://www.alliander.com/schemas/osgp/smartmetering/sm-configuration/2014/10
